name = "read-recommend"
main = "dist/server/server.js"
compatibility_date = "2024-09-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"

# Do not put secrets here! Configure them exclusively within the Cloudflare dashboard.

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
